
#===============
# DB
#===============
spring.datasource.url=jdbc:mysql://localhost:3306/rostam
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.initialization-mode=always
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

#===============================
# JPA / HIBERNATE
#===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.properties.hibernate.generate_statistics=true
#logging.level.org.hibernate.stat=debug
#logging.level.org.hibernate.type=trace

#===============
# JWT
#===============
jwt.signing.key.secret=rostamEcommerceSecurity2021
jwt.get.token.uri=/authenticate
jwt.refresh.token.uri=/refresh
jwt.http.request.header=Authorization
jwt.token.expiration.in.seconds=604800

#===============
# LOG4J
#===============
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.org.hibernate.SQL=error
