resilience4j:
  retry:
    instances:
      productService:
        max-attempts: 5
        wait-duration: 10s
  ratelimiter:
    instances:
      productService:
        register-health-indicator: false
        limit-for-period: 10
        limit-refresh-period: 10s
        timeout-duration: 3s